import { test, expect } from '../config/fixtures';

/**
 * EXAMPLE GENERATED TEST
 * Generated by: Builder Agent
 * Input Artifact: exploration-report.json
 * Confidence: 100%
 */

test.describe('Example Test Suite', () => {
  test('User can visit Playwright homepage', async ({ page }) => {
    // Navigation (Source URL from Explorer)
    await page.goto('https://playwright.dev/');

    // Assertion (Source Requirement: "Title must contain Playwright")
    await expect(page).toHaveTitle(/Playwright/);
  });
});
